### ISSUE TITLE
Regarding hosting issue with namecheap domain using github pages 

### ISSUE THREAD

**Issue by rudrakshkarpe** [antfu/antfu.me#33]
### Describe the bug

The build is completed successfully, but still, animations aren't opening after hosting using GitHub pages. The subpages show 404 error,

please help me fix this I'm stuck here since last 1 month 
https://www.rudrakshkarpe.me/portfolio/

### Reproduction

https://github.com/rudrakshkarpe/portfolio

### System Info

```Shell
chrome, Edge
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Please figure it out yourself, the code is there.

**Comment by rudrakshkarpe** [comment]
Thanks Anthony! I could fix the problem and it's working fine, you're awesome open sourceror
