### ISSUE TITLE
The post "Nuxt 3 or vitesse" seems unfinished

### ISSUE THREAD

**Issue by kingyue737** [antfu/antfu.me#43]
### Describe the bug

Publishing date is Nov 1, 2022 and estimated reading time is 12 mins. But it seems that this post is truncated. Did something unexpected happen, or to be continued? 

Looking forward to the complete post!

### Reproduction

https://antfu.me/posts/nuxt3-or-vitesse

### System Info

```Shell
Ignore
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Oh. I pushed it accidentally. Thanks.
