### ISSUE TITLE
Bug: Build over 200 lines of code blocks

### ISSUE THREAD

**Issue by JIeJaitt** [antfu/antfu.me#50]
### Describe the bug

When I created over 200 lines of code blocks in the markdown, there was an error in building the `pnpm run build`. If I delete it, it can be successfully built. I think it should be a bug.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/77219045/236879181-2a198e20-79b4-4182-a1a1-bca8ce233167.png">

### Reproduction

pnpm run build

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    npm: 9.6.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Emm, I am open source my blog for ppl to reference, not help fix every bug **you encounter**. Narrow it down and report to the corresponding tool.
