### ISSUE TITLE
build: the service started in the dist file, cannot find the page after refreshing.

### ISSUE THREAD

**Issue by shellingfordly** [antfu/antfu.me#66]
### Describe the bug

I have a question. After using npm to build, I use live-server to start the server in the dist file. There is no problem in initial entry, but the page cannot be found after refreshing, and the vercel build has the same problem. I recently discovered this problem while updating my blog. When I packaged your blog, I found that you had the same problem, but your online blog was normal. Why was this? How did you solve it?

Initially, I suspected that there was a routing problem after vite-plugin-pages was packaged. I found a similar builded problem in [vite-plugin-pages/issues#247](https://github.com/hannoeru/vite-plugin-pages/issues/247). Hope to get your help, I will close this issues.

<img width="638" alt="image-2" src="https://github.com/antfu/antfu.me/assets/39196952/ad0d03e8-79cd-4ac0-b871-87ca863c7ce1">

<img width="304" alt="image" src="https://github.com/antfu/antfu.me/assets/39196952/aac1a498-5edf-4e61-bad1-da01e1ff54ae">

### Reproduction

only cannot find the page after refreshing

### System Info

```Shell
cd antfu.me
pnpm run build
cd dist
live-server
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
`live-server --spa`
