### ISSUE TITLE
Autogenerated pages are not nested properly

### ISSUE THREAD

**Issue by bodobraegger** [antfu/antfu.me#70]
### Describe the bug

You would expect the Blog nav link to remain active when on a specific `posts/post`, but the `.md` pages are not recognized as children of the `posts` (or `notes`) index link by the router.

### Reproduction

Visit https://antfu.me/posts/animated-svg-logo, check the Blog nav link for .active-router-link class

### System Info

```Shell
This is not setup dependent, but is present in the compiled page output.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Thank you for bringing this up - but this is kinda what I expected.
