### ISSUE TITLE
Extended Features (Technical - Visual)

### ISSUE THREAD

**Issue by JARVIS-AI** [antfu/antfu.me#81]
### Clear and concise description of the problem

Hi there,
I hope you are doing well.
I have been reading your website and I really enjoy your work, have a few questions about adding some new features to your website:

**Mermaid diagrams**

I know that there is a Mermaid package that can be added to Vitepress, but this site is not built with Vitepress.

I have not seen any diagrams in your articles that have been written with Mermaid, but I would like to know if it has been implemented. If not, how can we implement it?

**Code block features**

In VitePress and other websites like nextjs.org, code blocks have the following features:

- Language type in the top right corner, e.g : py-ts-js-cpp-sh-perl- ...
- A nav bar or a status bar above the code block for information such as the file address and name etc ...
- Code focus and highlight features etc ... (which some of are implemented in vitepress doc)

How can these features be added to this site?

I notice that when I read the code examples in your articles, there is no copy button, information bar, or language icon for the code snippet.

**Using VitePress features**

How can I use Vitepress and vitepress doc features on this site, especially the Markdown writing features?
Thank you for your time and consideration.

Best regards,

### Suggested solution

I can add MathJax with the markdown-it MathJax package, but what about Mermaid? What if we can utilize VitePress Doc's MathJax and Mermaid native features in your website and incorporate them into .md posts?

As for Code Focus and Code block features, aside from CSS workarounds, are there any other logical ways to achieve what we want?

Antfu's website is great, but it lacks the awesome features found in your other works. 

Of course, if we consider the blog page and its posts as personal articles, then they don't necessarily need code block features like Next.js Doc or VitePress Doc provide. However, if we intend to create more technical articles and style them as documentation, it would be great to have code block features such as code focus and code highlighting etc ...

### Additional context

Markdown feature 
https://vitepress.dev/guide/markdown

Nextjs code block style
https://nextjs.org/docs/getting-started/installation

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JARVIS-AI** [comment]
Thank you for considering the suggestions and for sharing your perspective. It's completely understandable that simplicity is a priority for your website, especially if it's not intended to be a technical documentation platform.

That said, I respect your decision to prioritize simplicity, and I'm here to support whatever direction you choose for your website. If there comes a time when you feel these features would enhance your content, I'd be more than happy to assist with their implementation.

Best regards

**Comment by skyline523** [comment]
Hi there, I've looked at the vitepress source and referenced most of the code to implement the custom-block and code-group functionality, you can take a look at my project [leet.me](https://github.com/skyline523/leet.me)
