### ISSUE TITLE
build error in netlify, but it can be built in local

### ISSUE THREAD

**Issue by skyline523** [antfu/antfu.me#92]
### Describe the bug

on netlify, when rendering pages, error occur in /nav page: Cannot convert undefined or null to object. I think navs is empty, so i  give it the `{}`(`Object.keys(projects || {})`). And other pages frontmatter render error, and i try deploying on netlify again, it work. but all pages renders frontmatter is wrong, like this.
![image](https://github.com/user-attachments/assets/b24bb0e5-bd72-47f0-8208-efe15a0bd0e3)

deploy error info:
![image](https://github.com/user-attachments/assets/9f752e2e-b2d7-4f7f-afb1-83b5617360d2)

### Reproduction

https://github.com/skyline523/leet.me

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13400F
    Memory: 4.52 GB / 15.85 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.0 - E:\personal\leet.me\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by skyline523** [comment]
https://leetme.netlify.app/  can see effect that given `Object.keys(projects || {})`  , nav page is very confusing

**Comment by antfu** [comment]
I am sorry this repo is "just open source". I don't provide any help for your fork.
